-- Auto-generated seed recipes from desktop app library
-- These are visible to all users via visibility='system' + RLS policy

insert into public.recipes
  (owner_id, name, diets, servings, prep_minutes, cook_minutes,
   ingredients, steps, tags, protein_tag, visibility)
values
  (null, 'Lemon garlic chicken with broccoli', '{"omnivore","mediterranean","gluten-free","keto"}', 4, 10, 25, '[{"ingredientId":"chicken-breast","amount":1.5,"unit":"lb"},{"ingredientId":"broccoli","amount":1,"unit":"whole"},{"ingredientId":"lemon","amount":1,"unit":"whole"},{"ingredientId":"garlic","amount":4,"unit":"clove"},{"ingredientId":"olive-oil","amount":3,"unit":"tbsp"},{"ingredientId":"salt","amount":1,"unit":"tsp"},{"ingredientId":"black-pepper","amount":0.5,"unit":"tsp"}]'::jsonb, '["Pat chicken dry, season with salt and pepper.","Sear chicken in olive oil until golden, ~5 min/side.","Add minced garlic and lemon juice; finish in oven 10 min at 400°F.","Steam broccoli; toss with olive oil and salt."]'::jsonb, '{"quick","one-pan"}', 'chicken', 'system'),
  (null, 'Beef bolognese with penne', '{"omnivore"}', 4, 10, 35, '[{"ingredientId":"ground-beef","amount":1,"unit":"lb"},{"ingredientId":"pasta","amount":1,"unit":"lb"},{"ingredientId":"crushed-tomatoes","amount":28,"unit":"oz"},{"ingredientId":"tomato-paste","amount":2,"unit":"tbsp"},{"ingredientId":"yellow-onion","amount":1,"unit":"whole"},{"ingredientId":"garlic","amount":3,"unit":"clove"},{"ingredientId":"carrot","amount":4,"unit":"oz"},{"ingredientId":"olive-oil","amount":2,"unit":"tbsp"},{"ingredientId":"parmesan","amount":2,"unit":"oz"},{"ingredientId":"oregano","amount":1,"unit":"tsp"},{"ingredientId":"salt","amount":1,"unit":"tsp"}]'::jsonb, '["Dice onion and carrot finely; mince garlic.","Sauté veg in olive oil until soft, ~8 min.","Brown beef; add tomato paste, cook 2 min.","Add crushed tomatoes, oregano, salt; simmer 20 min.","Cook pasta; toss with sauce. Top with parmesan."]'::jsonb, '{"comfort","family"}', 'beef', 'system'),
  (null, 'Salmon quinoa bowl with greens', '{"pescatarian","omnivore","mediterranean","gluten-free"}', 2, 10, 20, '[{"ingredientId":"salmon","amount":0.75,"unit":"lb"},{"ingredientId":"quinoa","amount":0.5,"unit":"lb"},{"ingredientId":"spinach","amount":3,"unit":"oz"},{"ingredientId":"lemon","amount":1,"unit":"whole"},{"ingredientId":"olive-oil","amount":2,"unit":"tbsp"},{"ingredientId":"garlic","amount":2,"unit":"clove"},{"ingredientId":"salt","amount":0.5,"unit":"tsp"}]'::jsonb, '["Cook quinoa per package directions.","Season salmon with salt and lemon zest; bake at 400°F for 12 min.","Wilt spinach with garlic in olive oil.","Bowl: quinoa base, salmon, spinach, lemon wedge."]'::jsonb, '{"healthy","meal-prep"}', 'fish', 'system'),
  (null, 'Coconut chickpea curry', '{"vegan","vegetarian","gluten-free"}', 4, 10, 25, '[{"ingredientId":"chickpeas","amount":30,"unit":"oz"},{"ingredientId":"crushed-tomatoes","amount":14,"unit":"oz"},{"ingredientId":"yellow-onion","amount":1,"unit":"whole"},{"ingredientId":"garlic","amount":4,"unit":"clove"},{"ingredientId":"ginger","amount":1,"unit":"tbsp"},{"ingredientId":"cumin","amount":1,"unit":"tsp"},{"ingredientId":"paprika","amount":1,"unit":"tsp"},{"ingredientId":"rice","amount":0.5,"unit":"lb"},{"ingredientId":"olive-oil","amount":2,"unit":"tbsp"},{"ingredientId":"cilantro","amount":0.25,"unit":"whole"},{"ingredientId":"salt","amount":1,"unit":"tsp"}]'::jsonb, '["Sauté onion until soft. Add minced garlic and ginger.","Stir in cumin and paprika, toast 30 sec.","Add tomatoes and chickpeas; simmer 15 min.","Serve over rice, topped with cilantro."]'::jsonb, '{"budget","pantry"}', 'beans', 'system'),
  (null, 'Sesame tofu stir-fry', '{"vegan","vegetarian"}', 3, 15, 15, '[{"ingredientId":"tofu","amount":14,"unit":"oz"},{"ingredientId":"broccoli","amount":1,"unit":"whole"},{"ingredientId":"bell-pepper","amount":1,"unit":"whole"},{"ingredientId":"carrot","amount":4,"unit":"oz"},{"ingredientId":"garlic","amount":3,"unit":"clove"},{"ingredientId":"ginger","amount":1,"unit":"tbsp"},{"ingredientId":"soy-sauce","amount":3,"unit":"tbsp"},{"ingredientId":"rice","amount":0.5,"unit":"lb"},{"ingredientId":"olive-oil","amount":2,"unit":"tbsp"}]'::jsonb, '["Press tofu, cube, pan-fry until golden.","Stir-fry vegetables with garlic and ginger.","Add tofu back, splash with soy sauce.","Serve over rice."]'::jsonb, '{"quick","weeknight"}', 'tofu', 'system'),
  (null, 'Mediterranean grain bowl', '{"vegetarian","mediterranean"}', 2, 15, 15, '[{"ingredientId":"quinoa","amount":0.5,"unit":"lb"},{"ingredientId":"chickpeas","amount":15,"unit":"oz"},{"ingredientId":"cucumber","amount":1,"unit":"whole"},{"ingredientId":"cherry-tomato","amount":0.5,"unit":"lb"},{"ingredientId":"feta","amount":3,"unit":"oz"},{"ingredientId":"parsley","amount":0.25,"unit":"whole"},{"ingredientId":"lemon","amount":1,"unit":"whole"},{"ingredientId":"olive-oil","amount":3,"unit":"tbsp"},{"ingredientId":"salt","amount":0.5,"unit":"tsp"}]'::jsonb, '["Cook quinoa.","Chop cucumber, halve tomatoes, crumble feta.","Whisk olive oil and lemon juice for dressing.","Layer everything, top with parsley and dressing."]'::jsonb, '{"no-cook","fresh"}', 'beans', 'system'),
  (null, 'Garlic shrimp scampi', '{"pescatarian","omnivore"}', 3, 5, 15, '[{"ingredientId":"shrimp","amount":1,"unit":"lb"},{"ingredientId":"pasta","amount":0.5,"unit":"lb"},{"ingredientId":"garlic","amount":5,"unit":"clove"},{"ingredientId":"butter","amount":3,"unit":"tbsp"},{"ingredientId":"olive-oil","amount":2,"unit":"tbsp"},{"ingredientId":"lemon","amount":1,"unit":"whole"},{"ingredientId":"parsley","amount":0.25,"unit":"whole"},{"ingredientId":"red-pepper-flakes","amount":0.5,"unit":"tsp"},{"ingredientId":"salt","amount":0.5,"unit":"tsp"}]'::jsonb, '["Cook pasta to al dente.","Sauté garlic in butter and oil 30 sec.","Add shrimp; cook 2 min/side until pink.","Toss with pasta, lemon juice, parsley, red pepper."]'::jsonb, '{"quick","date-night"}', 'fish', 'system'),
  (null, 'Ground turkey tacos', '{"omnivore","gluten-free"}', 4, 10, 15, '[{"ingredientId":"ground-turkey","amount":1,"unit":"lb"},{"ingredientId":"corn-tortillas","amount":8,"unit":"whole"},{"ingredientId":"red-onion","amount":0.5,"unit":"whole"},{"ingredientId":"avocado","amount":1,"unit":"whole"},{"ingredientId":"lime","amount":1,"unit":"whole"},{"ingredientId":"cilantro","amount":0.25,"unit":"whole"},{"ingredientId":"cumin","amount":1,"unit":"tsp"},{"ingredientId":"paprika","amount":1,"unit":"tsp"},{"ingredientId":"olive-oil","amount":1,"unit":"tbsp"},{"ingredientId":"salt","amount":0.5,"unit":"tsp"}]'::jsonb, '["Brown turkey with cumin and paprika.","Warm tortillas.","Slice avocado, dice onion, chop cilantro.","Build tacos; squeeze lime over top."]'::jsonb, '{"weeknight","kid-friendly"}', 'pork', 'system'),
  (null, 'Hearty lentil soup', '{"vegan","vegetarian","gluten-free"}', 4, 10, 35, '[{"ingredientId":"lentils","amount":8,"unit":"oz"},{"ingredientId":"veg-broth","amount":32,"unit":"oz"},{"ingredientId":"yellow-onion","amount":1,"unit":"whole"},{"ingredientId":"carrot","amount":6,"unit":"oz"},{"ingredientId":"celery","amount":0.25,"unit":"whole"},{"ingredientId":"garlic","amount":3,"unit":"clove"},{"ingredientId":"crushed-tomatoes","amount":14,"unit":"oz"},{"ingredientId":"cumin","amount":1,"unit":"tsp"},{"ingredientId":"olive-oil","amount":2,"unit":"tbsp"},{"ingredientId":"salt","amount":1,"unit":"tsp"}]'::jsonb, '["Dice onion, carrot, celery; mince garlic.","Sauté in olive oil 8 min.","Add cumin, then lentils, broth, tomatoes.","Simmer 25 min until lentils are tender."]'::jsonb, '{"budget","meal-prep"}', 'beans', 'system'),
  (null, 'Keto sausage and spinach egg bake', '{"keto","vegetarian","gluten-free"}', 4, 10, 30, '[{"ingredientId":"eggs","amount":8,"unit":"whole"},{"ingredientId":"spinach","amount":5,"unit":"oz"},{"ingredientId":"mozzarella","amount":4,"unit":"oz"},{"ingredientId":"heavy-cream","amount":0.5,"unit":"cup"},{"ingredientId":"butter","amount":2,"unit":"tbsp"},{"ingredientId":"salt","amount":0.5,"unit":"tsp"},{"ingredientId":"black-pepper","amount":0.25,"unit":"tsp"}]'::jsonb, '["Wilt spinach in butter, drain excess liquid.","Whisk eggs with cream, salt, pepper.","Combine in baking dish, top with mozzarella.","Bake at 375°F for 25 min until set."]'::jsonb, '{"meal-prep","breakfast"}', 'eggs', 'system'),
  (null, 'Caprese avocado toast', '{"vegetarian","mediterranean"}', 2, 10, 5, '[{"ingredientId":"bread","amount":4,"unit":"whole"},{"ingredientId":"avocado","amount":1,"unit":"whole"},{"ingredientId":"tomato","amount":1,"unit":"whole"},{"ingredientId":"basil","amount":0.5,"unit":"whole"},{"ingredientId":"olive-oil","amount":1,"unit":"tbsp"},{"ingredientId":"vinegar-balsamic","amount":1,"unit":"tsp"},{"ingredientId":"salt","amount":0.25,"unit":"tsp"}]'::jsonb, '["Toast bread.","Mash avocado with salt; spread on toast.","Top with sliced tomato and basil.","Drizzle with oil and balsamic."]'::jsonb, '{"quick","breakfast","lunch"}', 'none', 'system'),
  (null, 'Chicken thigh tray bake with sweet potato', '{"omnivore","gluten-free","mediterranean"}', 4, 10, 40, '[{"ingredientId":"chicken-thigh","amount":1.5,"unit":"lb"},{"ingredientId":"sweet-potato","amount":2,"unit":"whole"},{"ingredientId":"red-onion","amount":1,"unit":"whole"},{"ingredientId":"garlic","amount":4,"unit":"clove"},{"ingredientId":"olive-oil","amount":3,"unit":"tbsp"},{"ingredientId":"paprika","amount":1,"unit":"tsp"},{"ingredientId":"oregano","amount":1,"unit":"tsp"},{"ingredientId":"salt","amount":1,"unit":"tsp"},{"ingredientId":"lemon","amount":1,"unit":"whole"}]'::jsonb, '["Cube sweet potato, wedge onion, smash garlic.","Toss veg with oil, salt, paprika, oregano.","Nestle thighs on top, squeeze lemon.","Roast at 425°F for 35–40 min until thighs hit 175°F."]'::jsonb, '{"one-pan","weeknight"}', 'chicken', 'system');
